meta_product_name: "MovieMojo"

meta_title: "MovieMojo - Quit overthinking your movie choice and start enjoying the show!"

meta_description: "Discover your perfect movie match with MovieMojo! Answer 5 simple questions and get 3 tailored movie suggestions to streamline your selection process. Say goodbye to endless browsing and hello to instant movie enjoyment with MovieMojo!"

meta_image: "meta_image.png" # should exist in `app/assets/images/`
